[package]
name = "prettypretty"
description = "Applying 2020s color science to 1970s terminal user interfaces"
keywords = ["awesome", "terminal", "color", "ANSI-escapes", "TUI"]
categories = ["command-line-interface", "gui", "graphics", "encoding"]
authors = ["Robert Grimm <rgrimm@alum.mit.edu>"]
version = "0.1.0"
edition = "2021"
repository = "https://github.com/apparebit/prettypretty"
license = "Apache-2.0"
include = ["/README.md", "/LICENSE", "/src"]
