[project]
name = "prettypretty"
description = "Applying 2020s color science to 1970s terminal user interfaces"
keywords = ["awesome", "terminal", "color", "ANSI escape code", "terminal user interface"]
readme = "README.md"
requires-python = ">=3.12"
license = {text = "Apache 2.0"}
authors = [{name = "Robert Grimm", email="rgrimm@alum.mit.edu"}]
dynamic = ["version"]

[project.optional-dependencies]
dev = ["flit", "ipython", "pyright"]
doc = [
    "sphinx",
    "sphinxcontrib-autoprogram",
    "sphinx-copybutton",
    "sphinx_design",
    "sphinx-rtd-theme",
]

[project.urls]
repository = "https://github.com/apparebit/prettypretty"
package = "https://pypi.org/project/prettypretty/"
documentation= "https://apparebit.github.io/prettypretty/"

[build-system]
requires = ["flit_core >=3.4"]
build-backend = "flit_core.buildapi"

[tool.pyright]
include = ["prettypretty/**/*.py", "test/*.py", "runtest.py"]
typeCheckingMode = "strict"
pythonVersion = "3.12"
