[project]
name = "pitty"
description = "Library support for awesome command line interfaces"
readme = "README.md"
requires-python = ">=3.12"
license = {text = "Apache 2.0"}
authors = [{name = "Robert Grimm", email="rgrimm@alum.mit.edu"}]
keywords= ["awesome terminals"]
dynamic = ["version"]

[project.optional-dependencies]
dev = ["pyright", "flit"]

[project.urls]
repository = "https://github.com/apparebit/pitty"

[build-system]
requires = ["flit_core >=3.4"]
build-backend = "flit_core.buildapi"

[tool.pyright]
include = ["pitty/**/*.py", "test/*.py", "runtest.py"]
typeCheckingMode = "strict"
pythonVersion = "3.12"
